-- Private per-app registration whitelists managed by Dashboard Manager.
begin;

create table if not exists public.report_allowed_users (id bigint generated by default as identity primary key, email text not null unique, added_by text, created_at timestamptz not null default now());
create table if not exists public.portal_allowed_users (id bigint generated by default as identity primary key, email text not null unique, added_by text, created_at timestamptz not null default now());
create table if not exists public.news_allowed_users (id bigint generated by default as identity primary key, email text not null unique, added_by text, created_at timestamptz not null default now());
create table if not exists public.bmi_allowed_users (id bigint generated by default as identity primary key, email text not null unique, added_by text, created_at timestamptz not null default now());

alter table public.report_allowed_users add column if not exists added_by text, add column if not exists created_at timestamptz not null default now();
alter table public.portal_allowed_users add column if not exists added_by text, add column if not exists created_at timestamptz not null default now();
alter table public.news_allowed_users add column if not exists added_by text, add column if not exists created_at timestamptz not null default now();
alter table public.bmi_allowed_users add column if not exists added_by text, add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists app_source text;

create or replace function public.is_dashboard_manager()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.dashboard_profiles where user_id = auth.uid()); $$;

create or replace function public.is_app_email_allowed(app_key text, candidate_email text)
returns boolean language plpgsql stable security definer set search_path = public
as $$
declare allowed boolean; whitelist_table text;
begin
  whitelist_table := case app_key
    when 'report' then 'report_allowed_users'
    when 'portal' then 'portal_allowed_users'
    when 'news' then 'news_allowed_users'
    when 'bmi' then 'bmi_allowed_users'
    else null
  end;
  if whitelist_table is null or candidate_email is null then return false; end if;
  execute format('select exists (select 1 from public.%I where lower(email) = lower($1))', whitelist_table)
    into allowed using trim(candidate_email);
  return allowed;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['report_allowed_users','portal_allowed_users','news_allowed_users','bmi_allowed_users'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('create policy "Dashboard managers can manage %1$s" on public.%1$I for all to authenticated using (public.is_dashboard_manager()) with check (public.is_dashboard_manager())', table_name);
    execute format('grant select, insert, update, delete on public.%I to authenticated', table_name);
  end loop;
end $$;

revoke all on function public.is_dashboard_manager() from public, anon;
grant execute on function public.is_dashboard_manager() to authenticated;
revoke all on function public.is_app_email_allowed(text, text) from public;
grant execute on function public.is_app_email_allowed(text, text) to anon, authenticated;

commit;
